
import java.awt.CardLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bobby
 */
public class DNDFRAME extends javax.swing.JFrame {

    /**
     * Creates new form DNDFRAME
     */
    public DNDFRAME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informationTab = new javax.swing.JTabbedPane();
        charPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        classLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        detailLabel = new javax.swing.JLabel();
        factionLabel = new javax.swing.JLabel();
        raceLabel = new javax.swing.JLabel();
        alignLabel = new javax.swing.JLabel();
        expLabel = new javax.swing.JLabel();
        strLabel = new javax.swing.JLabel();
        dexLabel = new javax.swing.JLabel();
        conLabel = new javax.swing.JLabel();
        intLabel = new javax.swing.JLabel();
        wisLabel = new javax.swing.JLabel();
        chaLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        classField = new javax.swing.JTextField();
        levelField = new javax.swing.JTextField();
        detailField = new javax.swing.JTextField();
        raceField = new javax.swing.JTextField();
        factionField = new javax.swing.JTextField();
        alignField = new javax.swing.JTextField();
        expField = new javax.swing.JTextField();
        strField = new javax.swing.JTextField();
        dexField = new javax.swing.JTextField();
        conField = new javax.swing.JTextField();
        intField = new javax.swing.JTextField();
        wisField = new javax.swing.JTextField();
        chaField = new javax.swing.JTextField();
        strModField = new javax.swing.JTextField();
        dexModField = new javax.swing.JTextField();
        conModField = new javax.swing.JTextField();
        intModField = new javax.swing.JTextField();
        wisModField = new javax.swing.JTextField();
        chaModField = new javax.swing.JTextField();
        dexUpdate = new javax.swing.JButton();
        strUpdate = new javax.swing.JButton();
        intUpdate = new javax.swing.JButton();
        conUpdate = new javax.swing.JButton();
        wisUpdate = new javax.swing.JButton();
        chaUpdate = new javax.swing.JButton();
        acLabel = new javax.swing.JLabel();
        acField = new javax.swing.JTextField();
        hpLabel = new javax.swing.JLabel();
        currenthpField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        maxhpField = new javax.swing.JTextField();
        iniLabel = new javax.swing.JLabel();
        iniField = new javax.swing.JTextField();
        speedLabel = new javax.swing.JLabel();
        speedField = new javax.swing.JTextField();
        techPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        techTextArea = new javax.swing.JTextArea();
        skillPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        skillTextArea = new javax.swing.JTextArea();
        invPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inventoryTextArea = new javax.swing.JTextArea();
        mainBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DND 5E CHARACTER SHEET");

        nameLabel.setText("Name:");

        classLabel.setText("Class:");

        levelLabel.setText("Level:");

        detailLabel.setText("Detail:");

        factionLabel.setText("Faction:");

        raceLabel.setText("Race:");

        alignLabel.setText("Align:");

        expLabel.setText("Exp:");

        strLabel.setText("Strength");

        dexLabel.setText("Dexterity");

        conLabel.setText("Constitution");

        intLabel.setText("Intelligence");

        wisLabel.setText("Wisdom");

        chaLabel.setText("Charisma");

        strField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strFieldActionPerformed(evt);
            }
        });

        dexField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dexFieldActionPerformed(evt);
            }
        });

        conField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conFieldActionPerformed(evt);
            }
        });

        intField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intFieldActionPerformed(evt);
            }
        });

        wisField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wisFieldActionPerformed(evt);
            }
        });

        chaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chaFieldActionPerformed(evt);
            }
        });

        strModField.setEditable(false);
        strModField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        strModField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strModFieldActionPerformed(evt);
            }
        });

        dexModField.setEditable(false);
        dexModField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dexModField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dexModFieldActionPerformed(evt);
            }
        });

        conModField.setEditable(false);
        conModField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        conModField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conModFieldActionPerformed(evt);
            }
        });

        intModField.setEditable(false);
        intModField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        intModField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intModFieldActionPerformed(evt);
            }
        });

        wisModField.setEditable(false);
        wisModField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        wisModField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wisModFieldActionPerformed(evt);
            }
        });

        chaModField.setEditable(false);
        chaModField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chaModField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chaModFieldActionPerformed(evt);
            }
        });

        dexUpdate.setText("Change");

        strUpdate.setText("Change");

        intUpdate.setText("Change");

        conUpdate.setText("Change");

        wisUpdate.setText("Change");

        chaUpdate.setText("Change");

        acLabel.setText("ARMOR CLASS:");

        hpLabel.setText("HIT POINTS:");

        jLabel17.setText("/");

        iniLabel.setText("INITIATIVE:");

        speedLabel.setText("SPEED:");

        javax.swing.GroupLayout charPanelLayout = new javax.swing.GroupLayout(charPanel);
        charPanel.setLayout(charPanelLayout);
        charPanelLayout.setHorizontalGroup(
            charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(charPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(charPanelLayout.createSequentialGroup()
                            .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(classLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameField)
                                .addComponent(classField)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, charPanelLayout.createSequentialGroup()
                            .addComponent(raceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(raceField, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, charPanelLayout.createSequentialGroup()
                            .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(levelField))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, charPanelLayout.createSequentialGroup()
                            .addComponent(factionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(factionField))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, charPanelLayout.createSequentialGroup()
                            .addComponent(detailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(detailField))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, charPanelLayout.createSequentialGroup()
                            .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(expLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(alignLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(alignField)
                                .addComponent(expField, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))
                    .addGroup(charPanelLayout.createSequentialGroup()
                        .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(strLabel)
                            .addGroup(charPanelLayout.createSequentialGroup()
                                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(strField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(strModField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(strUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dexLabel)
                            .addGroup(charPanelLayout.createSequentialGroup()
                                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dexField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dexModField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dexUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conLabel)
                            .addComponent(conModField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(charPanelLayout.createSequentialGroup()
                                .addComponent(conField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(charPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intLabel)
                            .addGroup(charPanelLayout.createSequentialGroup()
                                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(intField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(intModField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(intUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wisLabel)
                            .addComponent(wisModField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(charPanelLayout.createSequentialGroup()
                                .addComponent(wisField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wisUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chaModField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chaLabel)
                            .addGroup(charPanelLayout.createSequentialGroup()
                                .addComponent(chaField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(charPanelLayout.createSequentialGroup()
                        .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acLabel)
                            .addComponent(hpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iniLabel)
                            .addComponent(speedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(charPanelLayout.createSequentialGroup()
                                .addComponent(currenthpField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(maxhpField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(acField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speedField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iniField, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(0, 0, 0))
        );
        charPanelLayout.setVerticalGroup(
            charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(charPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acLabel)
                    .addComponent(acField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classLabel)
                    .addComponent(classField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpLabel)
                    .addComponent(currenthpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(maxhpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelLabel)
                    .addComponent(levelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniLabel)
                    .addComponent(iniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailLabel)
                    .addComponent(detailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speedLabel)
                    .addComponent(speedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raceLabel)
                    .addComponent(raceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(factionLabel)
                    .addComponent(factionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alignLabel)
                    .addComponent(alignField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expLabel)
                    .addComponent(expField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strLabel)
                    .addComponent(dexLabel)
                    .addComponent(conLabel)
                    .addComponent(intLabel)
                    .addComponent(wisLabel)
                    .addComponent(chaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(charPanelLayout.createSequentialGroup()
                        .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(strField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(wisUpdate)
                            .addComponent(chaUpdate))
                        .addGap(0, 0, 0)
                        .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(strModField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dexModField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conModField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intModField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wisModField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chaModField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(charPanelLayout.createSequentialGroup()
                        .addGroup(charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(strUpdate)
                            .addComponent(dexUpdate)
                            .addComponent(intUpdate))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        informationTab.addTab("Character", charPanel);

        techTextArea.setColumns(20);
        techTextArea.setRows(5);
        techTextArea.setText("Tech 1\nTech 2\nTech 3\nTech 4");
        jScrollPane1.setViewportView(techTextArea);

        javax.swing.GroupLayout techPanelLayout = new javax.swing.GroupLayout(techPanel);
        techPanel.setLayout(techPanelLayout);
        techPanelLayout.setHorizontalGroup(
            techPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );
        techPanelLayout.setVerticalGroup(
            techPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(techPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        informationTab.addTab("Tech/Spells", techPanel);

        skillTextArea.setColumns(20);
        skillTextArea.setRows(5);
        skillTextArea.setText("Skill 1\nSkill 2\nSkill 3\nSkill 4");
        jScrollPane2.setViewportView(skillTextArea);

        javax.swing.GroupLayout skillPanelLayout = new javax.swing.GroupLayout(skillPanel);
        skillPanel.setLayout(skillPanelLayout);
        skillPanelLayout.setHorizontalGroup(
            skillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );
        skillPanelLayout.setVerticalGroup(
            skillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(skillPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        informationTab.addTab("LifeSkills", skillPanel);

        inventoryTextArea.setColumns(20);
        inventoryTextArea.setRows(5);
        inventoryTextArea.setText("Item 1\nItem 2\nItem 3\nItem 4");
        jScrollPane3.setViewportView(inventoryTextArea);

        javax.swing.GroupLayout invPanelLayout = new javax.swing.GroupLayout(invPanel);
        invPanel.setLayout(invPanelLayout);
        invPanelLayout.setHorizontalGroup(
            invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );
        invPanelLayout.setVerticalGroup(
            invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        informationTab.addTab("Inventory", invPanel);

        jMenu1.setText("File");

        jMenuItem1.setText("New");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Open");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        mainBar.add(jMenu1);

        setJMenuBar(mainBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informationTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informationTab, javax.swing.GroupLayout.PREFERRED_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void strFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strFieldActionPerformed

    private void dexFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dexFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dexFieldActionPerformed

    private void conFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conFieldActionPerformed

    private void intFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intFieldActionPerformed

    private void wisFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wisFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wisFieldActionPerformed

    private void chaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chaFieldActionPerformed

    private void strModFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strModFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strModFieldActionPerformed

    private void dexModFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dexModFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dexModFieldActionPerformed

    private void conModFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conModFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conModFieldActionPerformed

    private void intModFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intModFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_intModFieldActionPerformed

    private void wisModFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wisModFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wisModFieldActionPerformed

    private void chaModFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chaModFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chaModFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DNDFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DNDFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DNDFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DNDFRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DNDFRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acField;
    private javax.swing.JLabel acLabel;
    private javax.swing.JTextField alignField;
    private javax.swing.JLabel alignLabel;
    public javax.swing.JTextField chaField;
    private javax.swing.JLabel chaLabel;
    private javax.swing.JTextField chaModField;
    private javax.swing.JButton chaUpdate;
    private javax.swing.JPanel charPanel;
    private javax.swing.JTextField classField;
    private javax.swing.JLabel classLabel;
    public javax.swing.JTextField conField;
    private javax.swing.JLabel conLabel;
    private javax.swing.JTextField conModField;
    private javax.swing.JButton conUpdate;
    private javax.swing.JTextField currenthpField;
    private javax.swing.JTextField detailField;
    private javax.swing.JLabel detailLabel;
    public javax.swing.JTextField dexField;
    private javax.swing.JLabel dexLabel;
    private javax.swing.JTextField dexModField;
    private javax.swing.JButton dexUpdate;
    private javax.swing.JTextField expField;
    private javax.swing.JLabel expLabel;
    private javax.swing.JTextField factionField;
    private javax.swing.JLabel factionLabel;
    private javax.swing.JLabel hpLabel;
    private javax.swing.JTabbedPane informationTab;
    private javax.swing.JTextField iniField;
    private javax.swing.JLabel iniLabel;
    public javax.swing.JTextField intField;
    private javax.swing.JLabel intLabel;
    private javax.swing.JTextField intModField;
    private javax.swing.JButton intUpdate;
    private javax.swing.JPanel invPanel;
    private javax.swing.JTextArea inventoryTextArea;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField levelField;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JMenuBar mainBar;
    private javax.swing.JTextField maxhpField;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField raceField;
    private javax.swing.JLabel raceLabel;
    private javax.swing.JPanel skillPanel;
    private javax.swing.JTextArea skillTextArea;
    private javax.swing.JTextField speedField;
    private javax.swing.JLabel speedLabel;
    public javax.swing.JTextField strField;
    private javax.swing.JLabel strLabel;
    private javax.swing.JTextField strModField;
    private javax.swing.JButton strUpdate;
    private javax.swing.JPanel techPanel;
    private javax.swing.JTextArea techTextArea;
    public javax.swing.JTextField wisField;
    private javax.swing.JLabel wisLabel;
    private javax.swing.JTextField wisModField;
    private javax.swing.JButton wisUpdate;
    // End of variables declaration//GEN-END:variables
}
